baseURL = "https://gonetoexplore.com"
languageCode = "en"
title = "Gone to Explore"
theme = "liva"

[params]
env = "production"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
hideSummary = false